language: python
dist: trusty
sudo: required

before_install:
  - [ "${TRAVIS_SECURE_ENV_VARS}" == "true" ] && openssl aes-256-cbc -K $encrypted_91bdf47b9392_key -iv $encrypted_91bdf47b9392_iv -in gh.json.enc -out ~/.gh.json -d

before_script:
  - npm rebuild
  - npm install -g gh

script:
  - python check_skills.py | tee ~/buildout.txt ; test ${PIPESTATUS[0]} -eq 0

after_failure:
  - '{ [ "${TRAVIS_PULL_REQUEST}" == "true" ] && [ "${TRAVIS_SECURE_ENV_VARS}" == "true" ] } && gh pr $TRAVIS_PULL_REQUEST --comment "`cat ~/buildout.txt`"'
